// <auto-generated>
// This code was auto-generated by the Mayope API builder.
// </auto-generated>

namespace Mayope.Api.Responses
{
    /// <summary>
    /// A response message (server -> client).
    /// </summary>
    public interface IResponse : IMessage
    {
    }
}
