// <auto-generated>
// This code was auto-generated by the Mayope API builder.
// </auto-generated>

namespace Mayope.Api.Responses
{
    /// <summary>
    /// A logout confirmation response.
    /// </summary>
    public class LogoutResponse : SuccessResponse
    {
    }
}
