// <auto-generated>
// This code was auto-generated by the Mayope API builder.
// </auto-generated>

namespace Mayope.Api
{
    /// <summary>
    /// A message.
    /// </summary>
    public interface IMessage
    {
    }
}
