// <auto-generated>
// This code was auto-generated by the Mayope API builder.
// </auto-generated>

using System.ComponentModel.DataAnnotations;

using Newtonsoft.Json;

namespace Mayope.Api.Types
{
    /// <summary>
    /// Details of a branch in a Mayope schema.
    /// </summary>
    public class Branch : Node
    {
        /// <summary>
        /// The type of the branch's value.
        /// </summary>
        [Required]
        [JsonRequired]
        public string Type { get; set; }

        /// <summary>
        /// The child branches if the type involves a Tree.
        /// </summary>
        public Branch Branches { get; set; }
    }
}
