// <auto-generated>
// This code was auto-generated by the Mayope API builder.
// </auto-generated>

namespace Mayope.Api.Requests
{
    /// <summary>
    /// A request message (client -> server).
    /// </summary>
    public interface IRequest : IMessage
    {
    }
}
