// <auto-generated>
// This code was auto-generated by the Mayope API builder.
// </auto-generated>

namespace Mayope.Api.Requests
{
    /// <summary>
    /// A request to log out, expiring the given token.
    /// </summary>
    public class LogoutRequest : AuthenticatedRequest
    {
    }
}
